<a href="https://colab.research.google.com/github/hmmnyamminji/bootcampproject/blob/main/Subway_market_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 서울시 행사 데이터

In [40]:
# 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 드라이브에 저장된 폰트 등록
import matplotlib as mpl
import matplotlib.pyplot as plt # 그래프를 그리는 모듈
import matplotlib.font_manager as fm # 폰트를 관리하는 모듈

# 드라이브 내 폰트 경로
font_path = '/content/drive/MyDrive/kwu/sub_project/font/NanumGothic.ttf'

fm.fontManager.addfont(font_path)
mpl.rc('font', family='NanumGothic') # matplotlib 기본 폰트로 설정
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['font.sans-serif'] = ['NanumGothic', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False # 마이너스(-) 기호가 깨지지 않도록 유니코드 마이너스 비활성화

print("현재 폰트: ", plt.rcParams['font.family']) # 현재 적용된 폰트 이름 출력

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
현재 폰트:  ['NanumGothic']

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import xml.etree.ElementTree as ET
import warnings # 코드 실행 중 발생하는 불필요한 경고 메시지를 숨김
warnings.filterwarnings('ignore')
import pprint
from sklearn.linear_model import LinearRegression
from datetime import datetime

## 인근 할인행사/직거래장터 정보

In [42]:
# https://data.seoul.go.kr/dataList/OA-15699/S/1/datasetView.do

In [43]:
df = pd.read_csv('/content/drive/MyDrive/kwu/sub_project/data/external/csv/서울시 할인행사_직거래장터 정보.csv',encoding='cp949')

TARGET_GU = ["강남구", "서초구", "마포구", "성동구", "중구", "송파구"]

df_filtered = df[df["구 이름"].isin(TARGET_GU)].copy()

df_filtered = df[df["구 이름"].isin(TARGET_GU)].copy()

df_filtered.head()

,일련번호,구 코드,구 이름,행사 코드,행사 이름,제목,내용,조회수,등록일,첨부파일경로
3,880,440000,마포구,1,할인행사,마포구 장바구니 생필품 물가 조사결과 &#40;10월 둘째주&#41;,2024년 10월 둘째주 장바구니 물가조사 결과입니다. 붙임문서를 참조 해 주십시오...,0,2024-10-17 15:38:09.0,NaN
78,805,200000,성동구,1,할인행사,성동형 공공배달앱 ＇배달특급＇ 공식 런칭!,낮은 수수료（1%）와 다양한 프로모션（할인쿠폰 등）으로 소상공인 및 소비자 모두 혜...,8,2022-07-20 16:10:15.0,NaN
85,798,140000,중구,1,할인행사,&#39;Welcome Back 명동&#39;이벤트 진행,- 버스킹부터 현장할인까지...명동 상권활성화 돕는다 - 서울 중구가 코로나19...,11,2022-06-15 16:22:50.0,NaN
93,790,710000,송파구,2,직거래장터,"&#39;우리동네 시장 나들이&#39;하고, 온누리상품권 받자!&#40;6/13~6...",이번 주&#40;6/13~6/17&#41; 우리동네 전통시장 나들이하고 온누리상품권...,3,2022-06-14 14:42:36.0,NaN
94,789,140000,중구,2,직거래장터,"신중앙시장, 전통시장 장보기 행사 14일 개최","신중앙시장, 전통시장 장보기 행사 14일 개최 - 5만원 이상 구매시 온누리상품권 ...",4,2022-06-13 18:20:11.0,NaN

In [45]:
columns_to_drop = ['일련번호','구 코드','행사 코드','내용','조회수','등록일', '첨부파일경로']
df_filtered = df_filtered.drop(columns=columns_to_drop, errors='ignore')

In [46]:
df_filtered.head()

   구 이름  행사 이름                                                 제목
3   마포구   할인행사             마포구 장바구니 생필품 물가 조사결과 &#40;10월 둘째주&#41;
78  성동구   할인행사                            성동형 공공배달앱 ＇배달특급＇ 공식 런칭!
85   중구   할인행사                    &#39;Welcome Back 명동&#39;이벤트 진행
93  송파구  직거래장터  &#39;우리동네 시장 나들이&#39;하고, 온누리상품권 받자!&#40;6/13~6...
94   중구  직거래장터                          신중앙시장, 전통시장 장보기 행사 14일 개최

## 인근 체육시설 공연행사 일정 (잠실)

In [ ]:
# https://data.seoul.go.kr/dataList/OA-15497/S/1/datasetView.do

In [62]:
import requests
import pandas as pd
import numpy as np

API_KEY = "696c51614b67696d3736727678634c"

url = f"http://openapi.seoul.go.kr:8088/{API_KEY}/json/stadiumScheduleInfo/1/1000/"

response = requests.get(url, timeout=10)
response.raise_for_status()

data = response.json()

df = pd.DataFrame(data['stadiumScheduleInfo']['row'])

print(df.head())

  SCH_SEQ               TITLE     SDATE     EDATE  \
0    3989   쇼트트랙 국가대표 최종 선발경기  20260411  20260412
1    3988           고교야구 주말리그  20260424  20260426
2    3987           고교야구 주말리그  20260417  20260419
3    3986  2026 KUSF U-리그 예선전  20260420  20260423
4    3985  2026 KUSF U-리그 예선전  20260413  20260416

                             USE_TIME USE_AGE USE_TARGET  \
0                              09:00~  전체 관람가     전체 관람가
1  24일(금) 15:00 / 25일(토)~26일(일) 09:30   전체 이용      전체 이용
2  17일(금) 15:00 / 18일(토)~19일(일) 09:30   전체 이용      전체 이용
3                              09:00~   전체 이용      전체 이용
4                               09:00   전체 이용      전체 이용

                         USE_PAY                                 LINK_URL  \
0                             없음  https://stadium.seoul.go.kr/about/mdice
1  http://www.seoulbsa.net/ (참조)                http://www.seoulbsa.net/
2  http://www.seoulbsa.net/ (참조)                http://www.seoulbsa.net/
3  http://www.seoulbsa.net/ (참조)                http://www.seoulbsa.net/
4  http://www.seoulbsa.net/ (참조)                http://www.seoulbsa.net/

                REG_DATE UPD_DATE SCH_CODE_A SCH_CODE_B CODE_TITLE_A  \
0  2026-04-09 16:53:29.0                   1         13        스포츠경기
1  2026-04-09 16:40:32.0                   1         12        스포츠경기
2  2026-04-09 16:38:35.0                   1         12        스포츠경기
3  2026-04-09 16:34:19.0                   1         12        스포츠경기
4  2026-04-09 16:33:16.0                   1         12        스포츠경기

  CODE_TITLE_B
0      목동실내빙상장
1        목동야구장
2        목동야구장
3        목동야구장
4        목동야구장

In [73]:
df_jamsil = df[df['CODE_TITLE_B'].str.contains('잠실', na=False)].copy()

df_jamsil['SDATE'] = pd.to_datetime(df_jamsil['SDATE'], format='%Y%m%d', errors='coerce')
df_jamsil['EDATE'] = pd.to_datetime(df_jamsil['EDATE'], format='%Y%m%d', errors='coerce')

df_jamsil = df_jamsil[
    (df_jamsil['SDATE'].dt.year >= 2023) & (df_jamsil['SDATE'].dt.year <= 2025)
].copy()

print(df_jamsil.head())

    SCH_SEQ            TITLE      SDATE      EDATE  \
78     3902     2025 잔나비 콘서트 2025-12-27 2025-12-28
79     3901     2025 크러쉬 콘서트 2025-12-19 2025-12-21
80     3900  2025 이찬원 연말 콘서트 2025-12-12 2025-12-14
98     3882   두산 야구단 팬 감사 행사 2025-11-23 2025-11-23
109    3871       LG야구단 팬 행사 2025-11-22 2025-11-22

                                              USE_TIME   USE_AGE USE_TARGET  \
78                   2025년 12월 27일(토) - 12월 28일(일) 17시   만 7세 이상    만 7세 이상
79   2025년 12월 19일(금) 19:30 [KST] 2025년 12월 20일(토) ...   만 7세 이상    만 7세 이상
80   2025년 12월 12일(금) 오후 7시 2025년 12월 13일(토) 오후 5시 ...   만 7세 이상    만 7세 이상
98                                              13:00~         -          -
109                                             13:00~  전체 이용 가능   전체 이용 가능

                                               USE_PAY  \
78   f'I'oor(현장수령)석 178,000원\r\nM석 178,000원\r\nJ석 1...
79                  VIP석\r\n165,000원\r\nR석\r\n154,000원
80                        VIP석 165,000원\r\nR석 143,000원
98                                                   -
109                                                  -

                                              LINK_URL               REG_DATE  \
78          https://www.ticketlink.co.kr/product/60144  2025-12-10 16:00:37.0
79        https://tickets.interpark.com/goods/25016006  2025-12-10 14:21:11.0
80                 https://ticket.yes24.com/Perf/55860  2025-12-10 14:16:04.0
98                            https://doosanbears.com/  2025-11-10 10:40:36.0
109  https://www.lgtwins.com/service/html.ncd?view=...  2025-10-31 14:58:29.0

                  UPD_DATE SCH_CODE_A SCH_CODE_B CODE_TITLE_A CODE_TITLE_B
78                                  2          9           공연      잠실실내체육관
79                                  2          9           공연      잠실실내체육관
80                                  2          9           공연      잠실실내체육관
98   2025-11-10 10:45:16.0          4          8           기타        잠실야구장
109  2025-11-10 10:45:36.0          4          8           기타        잠실야구장

In [75]:
columns_to_drop = ['LINK_URL','USE_PAY','CODE_TITLE_A','SCH_CODE_B','SCH_CODE_A','REG_DATE', 'UPD_DATE','USE_AGE','USE_TARGET','SCH_SEQ']
df_jamsil = df_jamsil.drop(columns=columns_to_drop, errors='ignore')

In [77]:
display(df_jamsil)

,TITLE,SDATE,EDATE,USE_TIME,CODE_TITLE_B
78,2025 잔나비 콘서트,2025-12-27,2025-12-28,2025년 12월 27일(토) - 12월 28일(일) 17시,잠실실내체육관
79,2025 크러쉬 콘서트,2025-12-19,2025-12-21,2025년 12월 19일(금) 19:30 [KST] 2025년 12월 20일(토) ...,잠실실내체육관
80,2025 이찬원 연말 콘서트,2025-12-12,2025-12-14,2025년 12월 12일(금) 오후 7시 2025년 12월 13일(토) 오후 5시 ...,잠실실내체육관
98,두산 야구단 팬 감사 행사,2025-11-23,2025-11-23,13:00~,잠실야구장
109,LG야구단 팬 행사,2025-11-22,2025-11-22,13:00~,잠실야구장
...,...,...,...,...,...
995,30주년 한터뮤직 어워즈,2023-02-10,2023-02-11,2022.02.10. ~ 02. 11.(이틀간 17:00~22:00),잠실실내체육관
996,프로농구(삼성:가스공사),2023-03-27,2023-03-27,19시,잠실실내체육관
997,프로농구(삼성:캐롯),2023-03-25,2023-03-25,17시,잠실실내체육관
998,프로농구(삼성:SK),2023-03-19,2023-03-19,17시,잠실실내체육관
999,프로농구(삼성:LG),2023-03-18,2023-03-18,15시,잠실실내체육관