<a href="https://colab.research.google.com/github/hmmnyamminji/bootcampproject/blob/main/Subway_market_info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
# 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

# 드라이브에 저장된 폰트 등록
import matplotlib as mpl
import matplotlib.pyplot as plt # 그래프를 그리는 모듈
import matplotlib.font_manager as fm # 폰트를 관리하는 모듈

# 드라이브 내 폰트 경로
font_path = '/content/drive/MyDrive/kwu/sub_project/font/NanumGothic.ttf'

fm.fontManager.addfont(font_path)
mpl.rc('font', family='NanumGothic') # matplotlib 기본 폰트로 설정
plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['font.sans-serif'] = ['NanumGothic', 'sans-serif']
plt.rcParams['axes.unicode_minus'] = False # 마이너스(-) 기호가 깨지지 않도록 유니코드 마이너스 비활성화

print("현재 폰트: ", plt.rcParams['font.family']) # 현재 적용된 폰트 이름 출력

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
현재 폰트:  ['NanumGothic']

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import xml.etree.ElementTree as ET
import warnings # 코드 실행 중 발생하는 불필요한 경고 메시지를 숨김
warnings.filterwarnings('ignore')
import pprint
from sklearn.linear_model import LinearRegression
from datetime import datetime

## 서울시 마켓 행사 (할인행사/직거래장터) 정보

In [42]:
# https://data.seoul.go.kr/dataList/OA-15699/S/1/datasetView.do

In [43]:
df = pd.read_csv('/content/drive/MyDrive/kwu/sub_project/data/external/csv/서울시 할인행사_직거래장터 정보.csv',encoding='cp949')

TARGET_GU = ["강남구", "서초구", "마포구", "성동구", "중구", "송파구"]

df_filtered = df[df["구 이름"].isin(TARGET_GU)].copy()

df_filtered = df[df["구 이름"].isin(TARGET_GU)].copy()

df_filtered.head()

,일련번호,구 코드,구 이름,행사 코드,행사 이름,제목,내용,조회수,등록일,첨부파일경로
3,880,440000,마포구,1,할인행사,마포구 장바구니 생필품 물가 조사결과 &#40;10월 둘째주&#41;,2024년 10월 둘째주 장바구니 물가조사 결과입니다. 붙임문서를 참조 해 주십시오...,0,2024-10-17 15:38:09.0,NaN
78,805,200000,성동구,1,할인행사,성동형 공공배달앱 ＇배달특급＇ 공식 런칭!,낮은 수수료（1%）와 다양한 프로모션（할인쿠폰 등）으로 소상공인 및 소비자 모두 혜...,8,2022-07-20 16:10:15.0,NaN
85,798,140000,중구,1,할인행사,&#39;Welcome Back 명동&#39;이벤트 진행,- 버스킹부터 현장할인까지...명동 상권활성화 돕는다 - 서울 중구가 코로나19...,11,2022-06-15 16:22:50.0,NaN
93,790,710000,송파구,2,직거래장터,"&#39;우리동네 시장 나들이&#39;하고, 온누리상품권 받자!&#40;6/13~6...",이번 주&#40;6/13~6/17&#41; 우리동네 전통시장 나들이하고 온누리상품권...,3,2022-06-14 14:42:36.0,NaN
94,789,140000,중구,2,직거래장터,"신중앙시장, 전통시장 장보기 행사 14일 개최","신중앙시장, 전통시장 장보기 행사 14일 개최 - 5만원 이상 구매시 온누리상품권 ...",4,2022-06-13 18:20:11.0,NaN

In [45]:
columns_to_drop = ['일련번호','구 코드','행사 코드','내용','조회수','등록일', '첨부파일경로']
df_filtered = df_filtered.drop(columns=columns_to_drop, errors='ignore')

In [46]:
df_filtered.head()

   구 이름  행사 이름                                                 제목
3   마포구   할인행사             마포구 장바구니 생필품 물가 조사결과 &#40;10월 둘째주&#41;
78  성동구   할인행사                            성동형 공공배달앱 ＇배달특급＇ 공식 런칭!
85   중구   할인행사                    &#39;Welcome Back 명동&#39;이벤트 진행
93  송파구  직거래장터  &#39;우리동네 시장 나들이&#39;하고, 온누리상품권 받자!&#40;6/13~6...
94   중구  직거래장터                          신중앙시장, 전통시장 장보기 행사 14일 개최